.TH "/home/esther/Escritorio/REDES-II/SSL/includes/G-2301-04-P3-redes2.h" 3 "Mon May 8 2017" "Servidor y cliente IRC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/esther/Escritorio/REDES-II/SSL/includes/G-2301-04-P3-redes2.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'G\-2301\-04\-P1\-socket\&.h'\fP
.br
\fC#include 'G\-2301\-04\-P1\-command\&.h'\fP
.br
\fC#include 'G\-2301\-04\-P2\-files\&.h'\fP
.br
\fC#include 'G\-2301\-04\-P2\-audio\&.h'\fP
.br
\fC#include 'G\-2301\-04\-P2\-messages\&.h'\fP
.br
\fC#include 'G\-2301\-04\-P2\-userCommands\&.h'\fP
.br
\fC#include 'G\-2301\-04\-P3\-ssl\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Modulo de redes2\&. Contiene todas las funciones de la libreria implementada\&. 
.PP
\fBAuthor:\fP
.RS 4
Antonio Amor Mourelle <antonio.amor@estudiante.uam.es> 
.PP
Esther Lopez Ramos <esther.lopezramos@estudiante.uam.es> 
.PP
Mario Santiago Yepes <mario.santiagoy@estudiante.uam.es> 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Servidor y cliente IRC from the source code\&.
