.TH "_" 3 "Mon May 8 2017" "Servidor y cliente IRC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_ \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <G\-2301\-04\-P1\-command\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBsck\fP"
.br
.ti -1c
.RI "SSL * \fBssl\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
estructura para guardar los argumentos de attendClient 
.SH "Field Documentation"
.PP 
.SS "sck"
socket en caso del cliente\&. Parametro obligtorio 
.SS "ssl"
Estructura ssl necesaria si se ha iniciado una conexion segura 

.SH "Author"
.PP 
Generated automatically by Doxygen for Servidor y cliente IRC from the source code\&.
