.TH "fileReceiver_args" 3 "Mon May 8 2017" "Servidor y cliente IRC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fileReceiver_args \- Estructura argumento de la funcion fileReceiver, con los parámetros necesarios para esta\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <G\-2301\-04\-P2\-files\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBsckF\fP"
.br
.ti -1c
.RI "char * \fBpath\fP"
.br
.ti -1c
.RI "long unsigned int \fBlength\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Estructura argumento de la funcion fileReceiver, con los parámetros necesarios para esta\&. 
.SH "Field Documentation"
.PP 
.SS "length"
Longitud del fichero 
.SS "path"
Ruta en la que se va a guardar el fichero 
.SS "sckF"
Socket en el que previamente se ha abierto la conexion con el otro extremo 

.SH "Author"
.PP 
Generated automatically by Doxygen for Servidor y cliente IRC from the source code\&.
